### ISSUE TITLE
Help on starting to implement botman in yii2

### ISSUE THREAD

**Issue by gasserol** [idk-tn/yii2-botman#2]
Hi, as you have solved the cache issue, I kindly ask your help for starting to integrated botman in yii2. I have an advanced template installed but have abolutely no idea where to write controller and all the rest that botman answers to requests. Du you have perhaps a short description on how to proceed? I now this is not a real issue, but I would gladly appreciate all your help! Many thanks, Oliver

**Comment by machour** [comment]
Hi @gasserol! No worries, glad to help get you started :)

My advice would be to first head to http://botman.io and go through their excellent documentation, if you haven't done so yet.

Then, start coding in one of your frontend controllers, using the WebDriver. Here's a sample code:

```php

class BotController extends Controller
{
     public $enableCsrfValidation = false;

    public function actionIndex()
    {
         // Set your driver
         DriverManager::loadDriver(WebDriver::class);
        // Create a botman instance
        $botman = BotManFactory::create([
                        'web' => [
                                'matchingData' => [
                                        'driver' => 'web',
                                ],
                        ]
                ], new Cache()); // <= The cache from yii2-botman

        $botman->hears('hello', function(BotMan $bot) {
              $bot->reply('world');
        });

        $botman->hears('*', function(BotMan $bot) {
              $bot->reply(sprintf('You said "%s", but I didn\'t understand that :/', $bot->getMessage()->getText()));
        });

        // start listening
        $botman->listen();
        // request must be terminated.
        die;
    }

}
``` 

Create a view with a form to post to that action:

```php
<div class="site-index">

    <div id="log">

    </div>

        <form class="row">
            <input class="form-control col-md-6" type="text" id="message" />
            <input class="form-control col-md-6" type="submit" />
        </form>
</div>

<?php

$this->registerJs(<<<SCRIPT
$("form").submit(function(e) {
    $.post('/bot', { driver: 'web', message: $('#message').val() }, function(j) {
        $('#log')[0].innerHTML += j.messages[0].text + "<br />";
    });
    return false;
});
SCRIPT
);
```

Try out your controller like that, and add more messages / [send back images](https://botman.io/2.0/sending#attachments) / urls / etc.

You can also use the [Web Widget](https://botman.io/2.0/driver-web#web-widget) instead of the lame form I've put up :)

After that, you would replace WebDriver by FacebookDriver or WhateverDriver you intend to use for your app, maybe make some code adjustments if needed. 

At this stage, you will probably know exactly if you want your bot to live in backend/frontend, or if you want to create a third dedicated endpoint.

Hope this helps :)

**Comment by gasserol** [comment]
@machour You are a genius! **Many thanks** for helping me, this is the first correct input for yii2 and botman! It works!
